---

docker_packages_prereqs:
- docker 
- docker-client
- docker-client-latest
- docker-common
- docker-latest
- docker-latest-logrotate
- docker-logrotate
- docker-engine

docker_packages:
- docker-ce
- docker-ce-cli
- containerd.io
